var exports = module.exports = {};

    exports.meals = [
  {
    title: "Beef Nacho Casserole",
    mealID: 1,
    ingredients: [ '1 pound ground beef',
  ' 1 1/2 cups chunky salsa',
  ' 1 (10 ounce) can whole kernel corn, drained',
  ' 3/4 cup creamy salad dressing (ie Miracle Whip)',
  ' 1 teaspoon chili powder',
  ' 2 cups crushed tortilla chips',
  ' 2 cups Colby cheese' ],
    instructions: "Preheat the oven to 350 degrees F (175 degrees C).  Place ground beef in a large skillet over medium-high heat. Cook, stirring to crumble, until evenly browned. Drain grease. Remove from the heat, and stir the salsa, corn, mayonnaise and chili powder into the beef. In a 2 quart casserole dish, layer the ground beef mixture, tortilla chips and cheese twice, ending with cheese on top.  Bake for 20 minutes uncovered in the preheated oven, until cheese is melted and dish is thoroughly heated." 
  },
  {
    title: "Avocado Watermelon Salad",
    mealID: 2,
    ingredients: [ '4 cups cubed watermelon',
  '  4 cups fresh baby spinach, torn',
  '  2 large avocados - peeled, pitted, and diced',
  '  1/4 cup walnut oil',
  '  1/4 cup olive oil',
  '  1 lime, juiced',
  '  1/2 teaspoon sweet paprika' ],
    instructions: "Combine watermelon, spinach, and avocados together in a bowl.  Whisk walnut oil, olive oil, lime juice, and paprika together in a bowl; pour over watermelon mixture. Toss to coat." 
  },
  {
    title: "Turkey Wraps",
    mealID: 3,
    ingredients: ['1 (8 ounce) package cream cheese with chives',
  '  2 tablespoons Dijon mustard',
  '  6 (8 inch) whole wheat tortillas',
  '  1 1/2 cups finely shredded iceberg lettuce',
  '  12 slices thinly sliced deli turkey',
  '  3/4 cup shredded Swiss cheese',
  '  1 large tomato, seeded and diced',
  '  1 large avocado, sliced',
  '  6 slices bacon, cooked and crumbled'],
    instructions: "Mix together the cream cheese and Dijon mustard until smooth. Spread each tortilla with about 2 tablespoons of the cream cheese mixture, spreading to within 1/4 inch of the edge of the tortillas.  Place 2 turkey slices per tortilla over the lettuce, and sprinkle with 2 tablespoons of shredded Swiss cheese. Top each tortilla evenly with tomato, avocado slices, and crumbled bacon." 
  },
  {
    title: "Honey Chicken Kabobs",
    mealID: 4,
    ingredients: ['1/4 cup vegetable oil',
  '  1/3 cup honey',
  '  1/3 cup soy sauce',
  '  1/4 teaspoon ground black pepper',
  '  2 cloves garlic',
  '  5 small onions, cut into 2 inch pieces',
  '  skewers',
  '  2 red bell peppers, cut into 2 inch pieces'],
    instructions: "Place the chicken, garlic, onions and peppers in the bowl, and marinate in the refrigerator at least 2 hours.  Preheat the grill for high heat.  Thread chicken and vegetables alternately onto the skewers.  Lightly oil the grill grate. Place the skewers on the grill. Cook for 12 to 15 minutes, until chicken juices run clear. Turn and brush with reserved marinade frequently." 
  },
  {
    title: "Grilled Bacon-Wrapped Corn on the Cob",
    mealID: 5,
    ingredients: ['10 ears corn, husked and cleaned',
  '  Cajun seasoning',
  '  salt and black pepper',
  '  1 (1 pound) package sliced bacon',
  '  10 12x8-inch sheets aluminum foil'],
    instructions: "Sprinkle each ear of corn with Cajun seasoning, salt, and pepper, and wrap each ear with 2 slices of bacon, covering the ear as completely as possible.  Wrap the ears in aluminum foil, twisting the ends tightly to seal.  Place the wrapped corn on the preheated grill, and grill on high heat until the corn is hot, about 10 minutes per side. Turn the heat to Low, and grill the corn until the bacon is cooked and the corn is tender, about 45 minutes." 
  },
  {
    title: "Buffalo Chicken Wings ",
    mealID: 6,
    ingredients: ['12 chicken wings',
  '  3 tablespoons butter',
  '  1/4 cup all-purpose flour',
  '  1 tablespoon distilled white vinegar',
  '  3 teaspoons hot pepper sauce',
  '  1/4 teaspoon salt',
  '  1/2 cup blue cheese salad dressing'],
    instructions: "Preheat oven to 350 degrees F (175 degrees C). Melt 2 tablespoons butter in a 9x13 inch baking dish in preheated oven. Coat chicken with flour, shake off excess and place in dish.  Bake uncovered in preheated oven for 20 minutes. In a small bowl combine the remaining 1 tablespoon butter, vinegar, pepper sauce and salt and mix until well blended. Add chicken and toss until evenly coated with mixture. Serve with bleu cheese salad dressing." 
  },
  {
    title: "Southern Fried Chicken Strips",
    mealID: 7,
    ingredients: ['30 saltine crackers',
  '  2 tablespoons dry potato flakes',
  ' 1 teaspoon seasoned salt',
  '  1 egg',
  '  1/2 cup all-purpose flour',
  '  3 skinless, boneless chicken breast halves, cut into 1-inch strips',
  '  1/4 cup vegetable oil'],
    instructions: "Mix cracker crumbs, potato flakes, seasoned salt, and black pepper together in a shallow bowl. Beat egg in a separate small bowl. Place flour in a third shallow bowl.  Heat vegetable oil in a large skillet over medium heat. Pan-fry chicken strips until no longer pink in the center and coating is golden brown, 15 to 20 minutes." 
  },
  {
    title: "Brownie Cupcakes",
    mealID: 8,
    ingredients: ['1 cup butter',
  '  1 cup chocolate chips',
  '  4 eggs',
  '  1 1/2 cups white sugar',
  '  1 cup all-purpose flour',
  '  1 teaspoon vanilla extract'],
    instructions: "Preheat oven to 325 degrees F.  Line 18 cupcake cups with paper liners. Melt butter and chocolate chips together in a saucepan over low heat, stirring until smooth; let cool.  Mix flour and vanilla extract into egg mixture. Fold in chocolate mixture until batter is smooth. Pour batter into prepared cupcake cups, filling them about 1/2 full. Bake 30 minutes." 
  },
  {
    title: "Pita Pizza",
    mealID: 9,
    ingredients: ['6 pita breads',
  '  1 (6.5 ounce) can tomato sauce',
  '  1 ounce diced pimento peppers, drained',
  '  2 small tomatoes',
  '  4 ounces shredded mozzarella cheese',
  '  4 ounces blue cheese, crumbled',
  '  1 pinch dried basil',
  '  1 pinch dried oregano'],
    instructions: "Preheat oven to 425 degrees F. Spread lightly with tomato sauce, pressing to flatten while spreading. Sprinkle with black olives, pimento peppers, tomatoes, mozzarella cheese, blue cheese, basil, oregano and coriander. Spread the pitas on a large baking sheet and place in the preheated oven 8 minute" 
  },
  {
    title: "Apple Snack Squares",
    mealID: 10,
    ingredients: ['2 cups white sugar',
  '  2 eggs',
  '  3/4 cup vegetable oil',
  '  1 teaspoon vanilla extract',
  '  2 1/2 cups self-rising flour',
  '  1 teaspoon ground cinnamon',
  '  3 apples',
  '  1 cup chopped walnuts'],
    instructions: "Preheat oven to 350 degrees. n a large bowl, combine the sugar, eggs, oil and vanilla and mix until well blended. Stir in the flour and cinnamon. The mixture will be thick. Fold in the chopped apple and nuts. Spread the batter in the prepared baking dish, and sprinkle with butterscotch chips.  Bake 40 minutes" 
  },
];
